version: '3.8'

services: 
    mongodb:
      image: mongo:5.0.2
      restart: unless-stopped
      volumes:
        - db:/data/db
    api:
      image: teerasej/people-web-api
      depends_on:
        - mongodb
      restart: unless-stopped

volumes:
  db: